# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
      env:
        DOTNET_NUGET_SIGNATURE_VERIFICATION: false
        
    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish
      run: dotnet publish --no-build -c Release -o ./publish
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: blazorday-website
        path: ./src/publish

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment: blazor-day-production

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: blazorday-website
        path: ./publish

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: 'publish/wwwroot'        # le dossier de sortie du build
        output_location: ''            # vide pour la plupart des apps .NET
        action: "upload"
